---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/xenial64

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[lib_template_test::default]
    verifier:
      inspec_tests:
#        - path: test/inspec/lib_template_test
      - name: lib_template_test
        url: https://p34r50n.net/inspec/lib_template_test.tar.gz
    attributes:
