---
driver:
  name: ec2
  aws_ssh_key_id: barclays-windows
  region: eu-west-2
  availability_zone: a
  image_id: ami-9c363cf8
  subnet_id: subnet-b2d331c9
  instance_type: t2.medium
  security_group_ids: sg-7a509e13
  retryable_tries: 120
  associate_public_ip: true
  tags:
    Name: rhel-kitchen

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /Users/warren/.ssh/barclays-windows.pem

platforms:
  - name: RHEL-7.3
    image_id: ami-9c363cf8

suites:
  - name: default
    run_list:
      - recipe[app_template_test::default]
    verifier:
      inspec_tests:
        - path: test/inspec/app_template_test
        - name: library template test
          path: ../../../lib_template_test/cookbooks/lib_template_test/test/inspec/lib_template_test
    attributes:
